name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            chip: [esp32, esp32c2, esp32c3, esp32c6, esp32h2, esp32p4, esp32s2, esp32s3]

    steps:
      - name: Install espup
        run: cargo install espup

      - name: Install ESP toolchains
        run: espup install

      - name: Checkout esp-hal 🛎️
        uses: actions/checkout@v2.3.1
        with:
          repository: 'esp-rs/esp-hal'
          path: 'esp-hal'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
  

      - name: Build and Clone Documentation for ${{ matrix.chip }}
        run: |       
          cd ${{ github.workspace }}/esp-hal

          if [ "${{ matrix.chip }}" == "esp32" ] || [ "${{ matrix.chip }}" == "esp32s2" ] || [ "${{ matrix.chip }}" == "esp32s3" ]; then
            cargo +esp xtask build-documentation esp-hal ${{ matrix.chip }}
          else
            cargo +nightly xtask build-documentation esp-hal ${{ matrix.chip }}
          fi 
          
          if [[ "${{ matrix.chip }}" == "esp32" || "${{ matrix.chip }}" == "esp32s2" || "${{ matrix.chip }}" == "esp32s3" ]]; then
            TARGET="xtensa-${{ matrix.chip }}-none-elf"
          elif [[ "${{ matrix.chip }}" == "esp32c6" || "${{ matrix.chip }}" == "esp32h2" ]]; then
            TARGET="riscv32imac-unknown-none-elf"
          elif [[ "${{ matrix.chip }}" == "esp32c3" || "${{ matrix.chip }}" == "esp32c2" ]]; then
            TARGET="riscv32imc-unknown-none-elf"
          elif [[ "${{ matrix.chip }}" == "esp32p4" ]]; then
            TARGET="riscv32imafc-unknown-none-elf"
          fi

          DOC_PATH="${{ github.workspace }}/esp-hal/esp-hal/target/${TARGET}/doc/${{ matrix.chip }}"
          TARGET_DIR="${{ github.workspace }}/documentation/${{ matrix.chip }}"

          mkdir -p $TARGET_DIR
          cp -r $DOC_PATH/* $TARGET_DIR/

          cd

      - name: Install and Build site 🔧
        run: |
         curl -s -L https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
         zola build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
            branch: docs-ghpage
            folder: . # The folder the action should deploy.
